### ISSUE TITLE
Integer validation should include consideration that int64 would be returned as string

### ISSUE THREAD

**Issue by rudranil-das** [open-traffic-generator/snappi#115]
To reproduce the issue, please use ixia-c controller version 0.0.1-2289.
(Starting with this version int64 values are accepted in both number/string format and returned as string [to accommodate high int64 values in http transport]

Please use the following script (which uses set_config followed by get_config),

```
import snappi


def test_snappi():
    # create a new API instance where location points to controller
    api = snappi.api(location="https://localhost", verify=False)
    # and an empty traffic configuration to be pushed to controller later on
    cfg = api.config()

    # add two ports where location points to traffic-engine (aka ports)
    p1, p2 = cfg.ports.port(name="p1", location="localhost:5555").port(
        name="p2", location="localhost:5556"
    )

    # add layer 1 property to configure same speed on both ports
    ly = cfg.layer1.layer1(name="ly")[-1]
    ly.port_names = [p1.name, p2.name]
    ly.speed = ly.SPEED_1_GBPS

    # add a traffic flow
    f1 = cfg.flows.flow(name="flow p1->p2")[-1]
    # and assign source and destination port
    f1.tx_rx.port.tx_name, f1.tx_rx.port.rx_name = p1.name, p2.name

    # configure packet size, rate and duration for both flows
    f1.size.fixed = 128
    for f in cfg.flows:
        # send 1000 packets and stop
        f.duration.fixed_packets.packets = 1000
        # send 1000 packets per second
        f.rate.pps = 1000

    # configure packet with Ethernet, IPv4 and UDP headers for both flows
    eth1 = f1.packet.ethernet()[-1]

    # set source and destination MAC addresses
    eth1.src.value, eth1.dst.value = "00:AA:00:00:04:00", "00:AA:00:00:00:AA"

    print("Pushing traffic configuration ...")
    api.set_config(cfg)

    print("Get back traffic configuration ...")
    gcfg = api.get_config()
    print(gcfg)

    print("Test passed !")


if __name__ == "__main__":
    test_snappi()
```

And the following exception is seen due to the issue mentioned in subject line,
```
root@rd-athena-new:/home/keysight/athena/tests# python py/samples/test_snappi.py 
2021-09-30 12:21:48 [snappi.snappi] [WARNING] Certificate verification is disabled
Pushing traffic configuration ...
Get back traffic configuration ...
Traceback (most recent call last):
  File "py/samples/test_snappi.py", line 50, in <module>
    test_snappi()
  File "py/samples/test_snappi.py", line 43, in test_snappi
    gcfg = api.get_config()
  File "/usr/local/lib/python3.8/dist-packages/snappi/snappi.py", line 53463, in get_config
    return self._transport.send_recv(
  File "/usr/local/lib/python3.8/dist-packages/snappi/snappi.py", line 118, in send_recv
    return return_object.deserialize(response_dict)
  File "/usr/local/lib/python3.8/dist-packages/snappi/snappi.py", line 188, in deserialize
    self._decode(serialized_object)
  File "/usr/local/lib/python3.8/dist-packages/snappi/snappi.py", line 422, in _decode
    item = child[1]()._decode(item)
  File "/usr/local/lib/python3.8/dist-packages/snappi/snappi.py", line 412, in _decode
    property_value = child[1](
  File "/usr/local/lib/python3.8/dist-packages/snappi/snappi.py", line 430, in _decode
    self._validate_types(property_name, property_value)
  File "/usr/local/lib/python3.8/dist-packages/snappi/snappi.py", line 507, in _validate_types
    self.types_validation(property_value, _type, msg, details["format"], details.get(
  File "/usr/local/lib/python3.8/dist-packages/snappi/snappi.py", line 322, in types_validation
    raise TypeError(err_msg)
TypeError: Invalid 1000 format, expected int64 at <class 'snappi.snappi.FlowRate'> 
 got 1000 of type <class 'str'> , expected min 1
```

**Comment by ashutshkumr** [comment]
https://github.com/open-traffic-generator/snappi/releases/tag/v0.6.3
