### ISSUE TITLE
import snappi failing on MacOS 12.3.1 with python 3.9.12

### ISSUE THREAD

**Issue by ankur-sheth** [open-traffic-generator/snappi#171]
Similar to issue #162.

```sh
~ pip3 list
Package            Version
------------------ ---------
certifi            2021.10.8
charset-normalizer 2.0.12
decorator          5.1.1
grpcio             1.44.0
grpcio-tools       1.44.0
idna               3.3
jsonpath-ng        1.5.3
pip                22.1.1
ply                3.11
protobuf           3.15.0
PyYAML             6.0
requests           2.27.1
setuptools         60.10.0
six                1.16.0
snappi             0.7.37
typing_extensions  4.1.1
urllib3            1.26.9
wheel              0.37.1

➜  ~ python3
Python 3.9.12 (main, Mar 26 2022, 15:44:31)
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import snappi
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/snappi/otg_pb2_grpc.py", line 7, in <module>
    import otg_pb2 as otg__pb2
ModuleNotFoundError: No module named 'otg_pb2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/snappi/__init__.py", line 1, in <module>
    from .snappi import Config
  File "/opt/homebrew/lib/python3.9/site-packages/snappi/snappi.py", line 17, in <module>
    from snappi import otg_pb2_grpc as pb2_grpc
  File "/opt/homebrew/lib/python3.9/site-packages/snappi/otg_pb2_grpc.py", line 9, in <module>
    from snappi import otg_pb2 as otg__pb2
  File "/opt/homebrew/lib/python3.9/site-packages/snappi/otg_pb2.py", line 23, in <module>
    _CONFIG = DESCRIPTOR.message_types_by_name['Config']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

```

**Comment by ANISH-GOTTAPU** [comment]
I have seen the same issue with Linux, looks like protobuf version needs to upgraded as well

https://github.com/grpc/grpc/issues/29223

**Comment by Rangababu-R** [comment]
Protobuf isn't required. @ankur-sheth  could you uninstall protobuf and try

**Comment by Rangababu-R** [comment]
> Protobuf isn't required. @ankur-sheth could you uninstall protobuf and try installing freshly

never mind, issue persists. let me fix it
