### ISSUE TITLE
mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))

### ISSUE THREAD

**Issue by Deepankarkr** [open-traffic-generator/snappi#194]
Using Python Version 3.10.8
System Version:	macOS 12.6.1
Kernel Version:	Darwin 21.6.0
Chip:	Apple M1 Pro(arm)
Name: snappi
Version: 0.9.5
```
Python 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import snappi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/--/Applications/pyenv/lib/python3.10/site-packages/snappi/__init__.py", line 1, in <module>
    from .snappi import Config
  File "/Users/--/Applications/pyenv/lib/python3.10/site-packages/snappi/snappi.py", line 13, in <module>
    import grpc
  File "/Users/--/Applications/pyenv/lib/python3.10/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/--/Applications/pyenv/lib/python3.10/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/--/Applications/pyenv/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 0x0002): tried: '/Users/--/Applications/pyenv/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

**Comment by ashutshkumr** [comment]
@Deepankarkr could you please try installing grpc libraries separately and let us know if it works ?

```sh
python -m pip install grpcio
python -m pip install grpcio-tools
```

**Comment by ashutshkumr** [comment]
@Deepankarkr kindly reopen if you still see this issue.
